import { Language } from './types';

export const CROPS = [
  { en: 'Rice (Paddy)', hi: 'धान (चावल)', te: 'వరి (ధాన్యం)' },
  { en: 'Wheat', hi: 'गेहूं', te: 'గోధుమ' },
  { en: 'Cotton', hi: 'कपास', te: 'పత్తి' },
  { en: 'Sugarcane', hi: 'गन्ना', te: 'చెరకు' },
  { en: 'Maize', hi: 'मक्का', te: 'మొక్కజొన్న' },
  { en: 'Vegetables', hi: 'सब्जियां', te: 'కూరగాయలు' },
  { en: 'Chilli', hi: 'मिर्च', te: 'మిరప' },
];

export const PESTICIDES = [
  'Urea',
  'DAP',
  'Neem Oil',
  'Imidacloprid',
  'Glyphosate',
  'Organic Mix',
];

export const TRANSLATIONS = {
  en: {
    app_name: 'Manakrishi',
    login_title: 'Login to Manakrishi',
    name_label: 'Full Name',
    enter_name: 'Enter your name',
    phone_label: 'Mobile Number',
    send_otp: 'Send OTP',
    enter_otp: 'Enter OTP',
    verify_otp: 'Verify & Login',
    book_service: 'Book Spraying',
    my_bookings: 'My Bookings',
    home: 'Home',
    profile: 'Profile',
    select_crop: 'Select Crop',
    land_size: 'Land Size (Acres)',
    select_pesticide: 'Select Pesticide',
    location: 'Farm Location',
    get_location: 'Detect My Farm Location',
    loc_found: 'Location Locked',
    submit_request: 'Request Drone',
    status_requested: 'Requested',
    status_scheduled: 'Scheduled',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    admin_panel: 'Admin Panel',
    no_bookings: 'No active bookings.',
    logout: 'Logout',
    welcome: 'Welcome',
    action: 'Action',
    mark_scheduled: 'Mark Scheduled',
    mark_completed: 'Mark Completed',
    cancel_job: 'Cancel Job',
    switch_lang: 'Change Language',
    loading: 'Processing...',
    success_booking: 'Drone Request Sent!',
    drone_status: 'Drone Systems Online',
    weather: 'Wind: 5km/h N • Clear',
  },
  hi: {
    app_name: 'मानकृषि',
    login_title: 'मानकृषि में लॉग इन करें',
    name_label: 'पूरा नाम',
    enter_name: 'अपना नाम दर्ज करें',
    phone_label: 'मोबाइल नंबर',
    send_otp: 'ओटीपी भेजें',
    enter_otp: 'ओटीपी दर्ज करें',
    verify_otp: 'सत्यापित करें',
    book_service: 'छिड़काव बुक करें',
    my_bookings: 'मेरी बुकिंग',
    home: 'होम',
    profile: 'प्रोफाइल',
    select_crop: 'फसल चुनें',
    land_size: 'भूमि का आकार (एकड़)',
    select_pesticide: 'कीटनाशक चुनें',
    location: 'खेत का स्थान',
    get_location: 'मेरे खेत का स्थान पता करें',
    loc_found: 'स्थान प्राप्त हुआ',
    submit_request: 'ड्रोन का अनुरोध करें',
    status_requested: 'अनुरोधित',
    status_scheduled: 'निर्धारित',
    status_completed: 'पूर्ण',
    status_cancelled: 'रद्द',
    admin_panel: 'एडमिन पैनल',
    no_bookings: 'कोई बुकिंग नहीं मिली।',
    logout: 'लॉग आउट',
    welcome: 'स्वागत है',
    action: 'कार्रवाई',
    mark_scheduled: 'शेड्यूल करें',
    mark_completed: 'पूर्ण करें',
    cancel_job: 'रद्द करें',
    switch_lang: 'भाषा बदलें',
    loading: 'प्रक्रिया जारी है...',
    success_booking: 'बुकिंग सफल!',
    drone_status: 'ड्रोन सिस्टम ऑनलाइन',
    weather: 'हवा: 5km/h • साफ',
  },
  te: {
    app_name: 'మనకృషి',
    login_title: 'మనకృషికి లాగిన్ చేయండి',
    name_label: 'పూర్తి పేరు',
    enter_name: 'మీ పేరు నమోదు చేయండి',
    phone_label: 'మొబైల్ నంబర్',
    send_otp: 'OTP పంపండి',
    enter_otp: 'OTP నమోదు చేయండి',
    verify_otp: 'ధృవీకరించండి',
    book_service: 'స్ప్రేయింగ్ బుక్ చేయండి',
    my_bookings: 'నా బుకింగ్స్',
    home: 'హోమ్',
    profile: 'ప్రొఫైల్',
    select_crop: 'పంటను ఎంచుకోండి',
    land_size: 'భూమి వైశాల్యం (ఎకరాలు)',
    select_pesticide: 'మందును ఎంచుకోండి',
    location: 'పొలం లొకేషన్',
    get_location: 'నా పొలం లొకేషన్ గుర్తించండి',
    loc_found: 'లొకేషన్ తీసుకోబడింది',
    submit_request: 'డ్రోన్‌ను అభ్యర్థించండి',
    status_requested: 'అభ్యర్థించబడింది',
    status_scheduled: 'షెడ్యూల్ చేయబడింది',
    status_completed: 'పూర్తయింది',
    status_cancelled: 'రద్దు చేయబడింది',
    admin_panel: 'అడ్మిన్ ప్యానెల్',
    no_bookings: 'బుకింగ్స్ ఏవీ లేవు.',
    logout: 'లాగ్ అవుట్',
    welcome: 'స్వాగతం',
    action: 'చర్య',
    mark_scheduled: 'షెడ్యూల్ చేయండి',
    mark_completed: 'పూర్తయింది',
    cancel_job: 'రద్దు చేయండి',
    switch_lang: 'భాష మార్చండి',
    loading: 'ప్రాసెస్ జరుగుతోంది...',
    success_booking: 'బుకింగ్ విజయవంతమైంది!',
    drone_status: 'డ్రోన్ సిస్టమ్స్ ఆన్‌లైన్',
    weather: 'గాలి: 5km/h • నిర్మలం',
  },
};