import { Language } from './types';

export const CROPS = [
  { en: 'Rice (Paddy)', hi: 'धान (चावल)' },
  { en: 'Wheat', hi: 'गेहूं' },
  { en: 'Cotton', hi: 'कपास' },
  { en: 'Sugarcane', hi: 'गन्ना' },
  { en: 'Maize', hi: 'मक्का' },
  { en: 'Vegetables', hi: 'सब्जियां' },
];

export const PESTICIDES = [
  'Urea',
  'DAP',
  'Neem Oil',
  'Imidacloprid',
  'Glyphosate',
  'Organic Mix',
];

export const TRANSLATIONS = {
  en: {
    app_name: 'Manakrishi',
    login_title: 'Login to Manakrishi',
    name_label: 'Full Name',
    enter_name: 'Enter your name',
    phone_label: 'Mobile Number',
    send_otp: 'Send OTP',
    enter_otp: 'Enter OTP',
    verify_otp: 'Verify & Login',
    book_service: 'Book Spraying',
    my_bookings: 'My Bookings',
    home: 'Home',
    profile: 'Profile',
    select_crop: 'Select Crop',
    land_size: 'Land Size (Acres)',
    select_pesticide: 'Select Pesticide',
    location: 'Farm Location',
    get_location: 'Use Current Location',
    loc_found: 'Location Captured',
    submit_request: 'Submit Request',
    status_requested: 'Requested',
    status_scheduled: 'Scheduled',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    admin_panel: 'Admin Panel',
    no_bookings: 'No bookings found.',
    logout: 'Logout',
    welcome: 'Welcome',
    action: 'Action',
    mark_scheduled: 'Mark Scheduled',
    mark_completed: 'Mark Completed',
    cancel_job: 'Cancel Job',
    switch_lang: 'हिंदी में देखें',
    loading: 'Loading...',
    success_booking: 'Booking Successful!',
  },
  hi: {
    app_name: 'मानकृषि',
    login_title: 'मानकृषि में लॉग इन करें',
    name_label: 'पूरा नाम',
    enter_name: 'अपना नाम दर्ज करें',
    phone_label: 'मोबाइल नंबर',
    send_otp: 'ओटीपी भेजें',
    enter_otp: 'ओटीपी दर्ज करें',
    verify_otp: 'सत्यापित करें',
    book_service: 'छिड़काव बुक करें',
    my_bookings: 'मेरी बुकिंग',
    home: 'होम',
    profile: 'प्रोफाइल',
    select_crop: 'फसल चुनें',
    land_size: 'भूमि का आकार (एकड़)',
    select_pesticide: 'कीटनाशक चुनें',
    location: 'खेत का स्थान',
    get_location: 'वर्तमान स्थान का उपयोग करें',
    loc_found: 'स्थान प्राप्त हुआ',
    submit_request: 'अनुरोध भेजें',
    status_requested: 'अनुरोधित',
    status_scheduled: 'निर्धारित',
    status_completed: 'पूर्ण',
    status_cancelled: 'रद्द',
    admin_panel: 'एडमिन पैनल',
    no_bookings: 'कोई बुकिंग नहीं मिली।',
    logout: 'लॉग आउट',
    welcome: 'स्वागत है',
    action: 'कार्रवाई',
    mark_scheduled: 'शेड्यूल करें',
    mark_completed: 'पूर्ण करें',
    cancel_job: 'रद्द करें',
    switch_lang: 'Switch to English',
    loading: 'लोड हो रहा है...',
    success_booking: 'बुकिंग सफल!',
  },
};