import { Language } from './types';

export const CROPS = [
  { en: 'Rice (Paddy)', te: 'వరి (ధాన్యం)' },
  { en: 'Wheat', te: 'గోధుమ' },
  { en: 'Cotton', te: 'పత్తి' },
  { en: 'Sugarcane', te: 'చెరకు' },
  { en: 'Maize', te: 'మొక్కజొన్న' },
  { en: 'Vegetables', te: 'కూరగాయలు' },
  { en: 'Chilli', te: 'మిరప' },
];

export const PESTICIDES = [
  'Urea',
  'DAP',
  'Neem Oil',
  'Imidacloprid',
  'Glyphosate',
  'Organic Mix',
];

export const TRANSLATIONS = {
  en: {
    app_name: 'Manakrishi',
    login_title: 'Welcome Farmer',
    login_subtitle: 'Drone Spraying Service',
    name_label: 'Full Name',
    enter_name: 'Enter your name',
    phone_label: 'Mobile Number',
    send_otp: 'Get OTP',
    enter_otp: 'Enter OTP',
    verify_otp: 'Login',
    book_service: 'New Spraying Request',
    my_bookings: 'My Bookings',
    home: 'Home',
    profile: 'Profile',
    select_crop: 'Select Crop',
    land_size: 'Land Size (Acres)',
    select_pesticide: 'Select Pesticide',
    location: 'Farm Location',
    get_location: 'Pin Farm Location',
    loc_found: 'Location Set',
    submit_request: 'Submit Request',
    update_request: 'Update Request',
    status_requested: 'Requested',
    status_scheduled: 'Scheduled',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    admin_panel: 'Admin Panel',
    no_bookings: 'No bookings yet.',
    logout: 'Logout',
    welcome: 'Hello',
    action: 'Action',
    mark_scheduled: 'Approve & Schedule',
    mark_completed: 'Mark Completed',
    cancel_job: 'Cancel Request',
    switch_lang: 'Change Language',
    loading: 'Loading...',
    success_booking: 'Request Submitted!',
    success_update: 'Request Updated!',
    drone_status: 'Ready to Fly',
    weather: 'Wind: 5km/h • Clear',
    edit: 'Edit',
    back: 'Back',
    booking_details: 'Booking Details',
    total_bookings: 'Total Requests',
    acres_covered: 'Acres Covered',
  },
  te: {
    app_name: 'మనకృషి',
    login_title: 'రైతుకు స్వాగతం',
    login_subtitle: 'డ్రోన్ స్ప్రేయింగ్ సేవ',
    name_label: 'పూర్తి పేరు',
    enter_name: 'మీ పేరు',
    phone_label: 'మొబైల్ నంబర్',
    send_otp: 'OTP పొందండి',
    enter_otp: 'OTP నమోదు చేయండి',
    verify_otp: 'లాగిన్',
    book_service: 'కొత్త అభ్యర్థన',
    my_bookings: 'నా బుకింగ్స్',
    home: 'హోమ్',
    profile: 'ప్రొఫైల్',
    select_crop: 'పంటను ఎంచుకోండి',
    land_size: 'భూమి వైశాల్యం (ఎకరాలు)',
    select_pesticide: 'మందును ఎంచుకోండి',
    location: 'పొలం లొకేషన్',
    get_location: 'లొకేషన్ గుర్తించండి',
    loc_found: 'లొకేషన్ సెట్ చేయబడింది',
    submit_request: 'పంపండి',
    update_request: 'అప్‌డేట్ చేయండి',
    status_requested: 'అభ్యర్థించబడింది',
    status_scheduled: 'షెడ్యూల్ చేయబడింది',
    status_completed: 'పూర్తయింది',
    status_cancelled: 'రద్దు చేయబడింది',
    admin_panel: 'అడ్మిన్ ప్యానెల్',
    no_bookings: 'బుకింగ్స్ ఏవీ లేవు.',
    logout: 'లాగ్ అవుట్',
    welcome: 'నమస్కారం',
    action: 'చర్య',
    mark_scheduled: 'షెడ్యూల్ చేయండి',
    mark_completed: 'పూర్తయింది',
    cancel_job: 'రద్దు చేయండి',
    switch_lang: 'భాష మార్చండి',
    loading: 'లోడ్ అవుతోంది...',
    success_booking: 'విజయవంతమైంది!',
    success_update: 'అప్‌డేట్ చేయబడింది!',
    drone_status: 'సిద్ధంగా ఉంది',
    weather: 'గాలి: 5km/h • నిర్మలం',
    edit: 'సవరించు',
    back: 'వెనుకకు',
    booking_details: 'బుకింగ్ వివరాలు',
    total_bookings: 'మొత్తం అభ్యర్థనలు',
    acres_covered: 'ఎకరాలు పూర్తయ్యాయి',
  },
};